  
--- 
    services: 
      backend:
        container_name: backend
        image: springcommunity/spring-petclinic-rest:latest
        ports:
          - "9966:9966"
        networks:
          - petclinic

      frontend:
        container_name: frontend
        image: denzaaaaal/frontend:latest
        ports:
          - "4200:4200"
        networks:
          - petclinic

      nginx:
        container_name: reverse_proxy
        image: denzaaaaal/nginx:latest
        ports:
          - "4200:4200"
        networks:
          - petclinic
          
    networks:
      petclinic:
        driver: bridge

    version: "3.7"